version: '3.2'
services:
  nodejs-express-boilerplate:
    image: experimentallife/nodejs-express-boilerplate
    restart: always
    ports:
      - '4000:4000'
    networks:
      nodejs-express-boilerplate-network:
        ipv4_address: 192.168.1.2

networks:
  nodejs-express-boilerplate-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/28
