version: '3'

services:
  postgres:
    image: postgres:12.9-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker/postgres.env
    networks:
      develop-network:
        ipv4_address: 192.168.0.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 15432:80
    user: root
    env_file:
      - docker/pgadmin.env
    networks:
      develop-network:
        ipv4_address: 192.168.0.3
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      develop-network:
        ipv4_address: 192.168.0.4

networks:
  develop-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/29
          gateway: 192.168.0.1
